# Generated by Django 5.2.3 on 2025-06-20 01:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APPClient',
            fields=[
                ('client_name', models.CharField(max_length=24)),
                ('description', models.TextField()),
                ('client_id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
