# Generated by Django 5.2.3 on 2025-06-20 01:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appclient',
            name='client_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='appclient',
            name='client_name',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
