# Generated by Django 5.2.3 on 2025-06-20 01:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_appclient_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appclient',
            name='client_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
